Fiction\WorldBundle\Entity\World:
    type: entity
    repositoryClass: \Fiction\WorldBundle\Entity\WorldRepository
    table: world
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        created_at:
            type: datetime
        updated_at:
            type: datetime
    oneToMany:
    manyToOne:
        user:
            targetEntity: \Fiction\UserBundle\Entity\User
            inversedBy: worlds
            joinColumn:
                name: user_id
                referencedColumnName: id
        world_type:
            targetEntity: \Fiction\WorldBundle\Entity\WorldType
            inversedBy: worlds
            joinColumn:
                name: world_type_id
                referencedColumnName: id
    manyToMany:
        children:
            targetEntity: \Fiction\WorldBundle\Entity\World
            mappedBy: parents
        parents:
            targetEntity: \Fiction\WorldBundle\Entity\World
            inversedBy: children
            cascade: [persist]
            joinTable:
                name: parents
                joinColumns:
                    child_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    parent_id:
                        referencedColumnName: id                        
                    
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]
