create_fandom:
  path: /user/fandom/create
  defaults: { _controller: FictionFandomBundle:Fandom:createFandom }
  requirements: 
    
edit_fandom:
  path: /user/fandom/{fandomId}/edit
  defaults: { _controller: FictionFandomBundle:Fandom:editFandom }
  requirements:
    fandomId: \d+
    
delete_fandom:
  path: /user/fandom/{fandomId}/delete
  defaults: { _controller: FictionFandomBundle:Fandom:deleteFandom }
  requirements:
    fandomId: \d+
    
delete_confirm_fandom:
  path: /user/fandom/{fandomId}/delete/confirm
  defaults: { _controller: FictionFandomBundle:Fandom:deleteConfirmFandom }
  requirements:
    fandomId: \d+
   
create_chapter:
  path: /user/fandom/{fandomId}/chapter/create
  defaults: { _controller: FictionFandomBundle:Chapter:createChapter }
  requirements:
    fandomId: \d+
    
edit_chapter:
  path: /user/fandom/{fandomId}/chapter/{chapterNumber}/edit
  defaults: { _controller: FictionFandomBundle:Chapter:editChapter }
  requirements:
    fandomId: \d+
    chapterNumber: \d+

view_fandom:
  path: /fandom/{fandomId}
  defaults: { _controller: FictionFandomBundle:Fandom:viewFandom }
  requirements:
    page: \d+
    fandomId: \d+
  
view_fandom_children:
  path: /fandoms/{fandomId}/page/{page}
  defaults: { _controller: FictionFandomBundle:Fandom:viewFandomChildren }
  requirements:
    page: \d+
    fandomId: \d+

find_fandom:
  path: /fandoms/page/{page}
  defaults: { _controller: FictionFandomBundle:Fandom:findFandoms }
  requirements:
    page: \d+
  
user_fandoms:
  path: /user/fandoms
  defaults: { _controller: FictionFandomBundle:Fandom:userFandoms }
  requirements: 
  
view_chapter:
  path: /fandom/{fandomId}/chapter/{chapterNumber}
  defaults: { _controller: FictionFandomBundle:Chapter:viewChapter }
  requirements:
    fandomId: \d+
    chapterNumber: \d+ 