Fiction\FandomBundle\Entity\Fandom:
    properties:
        id:
            - Type:
                type: integer
                message: "{{ value }} is not a valid id. It must be an integer."
            - GreaterThan:
                value: 0
        title:
            - Length:
                min: 1
                max: 255
                minMessage: "The fandom title must be at least {{ limit }} character(s)."
                maxMessage: "The fandom title must be less than {{ limit }} characters."
            - NotBlank: ~
        description:
            - NotBlank: ~
            - Length:
                min: 1
                max: 1000
                minMessage: "The fandom description must be at least {{ limit }} character(s)."
                maxMessage: "The fandom description must be less than {{ limit }} characters."
        created_at:
            - DateTime: ~
        updated_at:
            - DateTime: ~
        word_count:
            - Type:
                type: integer
                message: "The word count must be an integer."
                
Fiction\FandomBundle\Entity\Chapter:
    properties:
        id:
            - Type:
                type: integer
                message: "{{ value }} is not a valid id. It must be an integer."
            - GreaterThan:
                value: 0
        title:
            - Length:
                min: 1
                max: 255
                minMessage: "The chapter title must have at least {{ limit }} characters."
                maxMessage: "The chapter title must be less than {{ limit }} characters."
            - NotBlank: ~
        content:
            - NotBlank: ~
        created_at:
            - DateTime: ~
        updated_at:
            - DateTime: ~
        chapter_number:
            - Type:
                type: integer
                message: "The word count must be an integer."
        word_count:
            - Type:
                type: integer
                message: "The word count must be an integer."
                
Fiction\FandomBundle\Entity\Category:
    properties:
        id:
            - Type:
                type: integer
                message: "{{ value }} is not a valid id. It must be an integer."
            - GreaterThan:
                value: 0
        name:
            - Length:
                min: 1
                max: 255
                minMessage: "The category's name must have at least {{ limit }} characters."
                maxMessage: "The category's name must be less than {{ limit }} characters."
            - NotBlank: ~
                
Fiction\FandomBundle\Entity\FandomType:
    properties:
        id:
            - Type:
                type: integer
                message: "{{ value }} is not a valid id. It must be an integer."
            - GreaterThan:
                value: 0
        name:
            - Length:
                min: 1
                max: 255
                minMessage: "The fandom type's name must have at least {{ limit }} characters."
                maxMessage: "The fandom type's name must be less than {{ limit }} characters."
            - NotBlank: ~