parameters:
#    fiction_user.example.class: Fiction\UserBundle\Example

services:
#    fiction_user.example:
#        class: %fiction_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
