<?php

namespace Fiction\WorldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends EntityRepository
{
	public function getWorldChapter($world, $chapterNumber)
	{
		$em = $this->getEntityManager();
		
		$query = $em->createQuery(
		    'SELECT c
		    FROM FictionWorldBundle:Chapter c
		    WHERE c.world = :world AND c.chapter_number = :chapter'
		)
		->setParameter(':world', $world)
		->setParameter(':chapter', $chapterNumber);
		
		return $query->getOneOrNullResult();
	}
	
	public function getAllWorldChapters($world)
	{
		$em = $this->getEntityManager();
	
		$query = $em->createQuery(
			'SELECT c
		    FROM FictionWorldBundle:Chapter c
		    WHERE c.world = :world
			ORDER BY c.chapter_number ASC'
		)
		->setParameter(':world', $world);
	
		return $query->getResult();
	}
	
	/**
	 * Returns chapters affected by changing a chapter number.
	 * 
	 * i.e moving chapter number 3 to chapter number 8 returns
	 * chapters 3 to 8 to be updated accordingly 
	 *  
	 * @param World $world
	 */
	public function getUpdatedWorldChapters($world, $startChapter, $endChapter)
	{
		$em = $this->getEntityManager();
		
		$query = $em->createQuery(
		    'SELECT c
		    FROM FictionWorldBundle:Chapter c
		    WHERE c.world = :world AND c.chapter_number >= :startChapter AND c.chapter_number <= :endChapter
			ORDER BY c.chapter_number ASC'
		)
		->setParameter(':world', $world)
		->setParameter(':startChapter', $startChapter)
		->setParameter(':endChapter', $endChapter);
		
		return $query->getResult();
	}
}
