homepage:
  path: /
  defaults: { _controller: FictionAppBundle:Default:index }
  
find_community:
  path: /find/communities
  defaults: { _controller: FictionAppBundle:Default:index }
  
error:
  path: /error
  defaults: { _controller: FictionAppBundle:Default:error }