homepage:
  path: /
  methods: [GET]
  defaults: { _controller: FictionAppBundle:Default:index }
  
find_community:
  path: /communities
  methods: [GET]
  defaults: { _controller: FictionAppBundle:Default:index }
  
error:
  path: /error
  defaults: { _controller: FictionAppBundle:Default:error }