Fiction\UserBundle\Entity\User:
  type: entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created_at:
      type: datetime
  oneToMany:
    worlds:
      targetEntity: \Fiction\WorldBundle\Entity\World
      mappedBy: user
  lifecycleCallbacks:
        prePersist: [setCreatedAtValue]