Fiction\StoryBundle\Entity\StoryCategory:
    type: entity
    table: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        stories:
            targetEntity: \Fiction\StoryBundle\Entity\Story
            mappedBy: categories
    lifecycleCallbacks: {  }
