create_world:
  path: /worlds/create
  defaults: { _controller: FictionWorldBundle:World:createWorld }
  methods: [GET, POST]
  requirements: 
    
edit_world:
  path: /worlds/{worldId}/edit
  defaults: { _controller: FictionWorldBundle:World:editWorld }
  methods: [GET, PUT]
  requirements:
    worldId: \d+
    
delete_world:
  path: /worlds/{worldId}/delete
  defaults: { _controller: FictionWorldBundle:World:deleteWorld }
  methods: [GET, DELETE]
  requirements:
    worldId: \d+
    
delete_confirm_world:
  path: /worlds/{worldId}/delete/confirm
  defaults: { _controller: FictionWorldBundle:World:deleteConfirmWorld }
  methods: [GET, DELETE]
  requirements:
    worldId: \d+
   
view_stories:
  path: /worlds/{worldId}/stories
  defaults: { _controller: FictionWorldBundle:World:viewStories }
  methods: [GET]
  requirements:
    worldId: \d+
    
user_worlds:
  path: /worlds
  defaults: { _controller: FictionWorldBundle:World:userWorlds }
  methods: [GET]
  requirements: