fiction_world_profile:
  resource: "@FictionWorldBundle/Resources/config/routing/profile.yml"
  prefix: "/profile"

view_world:
  path: /worlds/{worldId}
  defaults: { _controller: FictionWorldBundle:World:viewWorld }
  methods: [GET]
  requirements:
    page: \d+
    worldId: \d+
  
view_world_children:
  path: /worlds/{worldId}/page/{page}
  defaults: { _controller: FictionWorldBundle:World:viewWorldChildren }
  methods: [GET]
  requirements:
    page: \d+
    worldId: \d+

find_world:
  path: /worlds/page/{page}
  defaults: { _controller: FictionWorldBundle:World:findWorlds }
  methods: [GET]
  requirements:
    page: \d+ 