<?php

namespace Fiction\FandomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends EntityRepository
{
	public function getFandomChapter($fandom, $chapterNumber)
	{
		$em = $this->getEntityManager();
		
		$query = $em->createQuery(
		    'SELECT c
		    FROM FictionFandomBundle:Chapter c
		    WHERE c.fandom = :fandom AND c.chapter_number = :chapter'
		)
		->setParameter(':fandom', $fandom)
		->setParameter(':chapter', $chapterNumber);
		
		return $query->getOneOrNullResult();
	}
	
	public function getAllFandomChapters($fandom)
	{
		$em = $this->getEntityManager();
	
		$query = $em->createQuery(
			'SELECT c
		    FROM FictionFandomBundle:Chapter c
		    WHERE c.fandom = :fandom
			ORDER BY c.chapter_number ASC'
		)
		->setParameter(':fandom', $fandom);
	
		return $query->getResult();
	}
	
	/**
	 * Returns chapters affected by changing a chapter number.
	 * 
	 * i.e moving chapter number 3 to chapter number 8 returns
	 * chapters 3 to 8 to be updated accordingly 
	 *  
	 * @param Fandom $fandom
	 */
	public function getUpdatedFandomChapters($fandom, $startChapter, $endChapter)
	{
		$em = $this->getEntityManager();
		
		$query = $em->createQuery(
		    'SELECT c
		    FROM FictionFandomBundle:Chapter c
		    WHERE c.fandom = :fandom AND c.chapter_number >= :startChapter AND c.chapter_number <= :endChapter
			ORDER BY c.chapter_number ASC'
		)
		->setParameter(':fandom', $fandom)
		->setParameter(':startChapter', $startChapter)
		->setParameter(':endChapter', $endChapter);
		
		return $query->getResult();
	}
}
