<?php

namespace Fiction\FandomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FandomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FandomRepository extends EntityRepository
{

	public function findChildFandoms($fandomId, $perPage, $page = 1)
	{
		$query = $this->createQueryBuilder('f');
		
		$query->select('f, SIZE(f.chapters) AS chapter_count')
			->leftJoin('f.parents', 'p', 'WHERE', 'p.id = :id')
			->setParameter(':id', $fandomId)
			->orderBy('f.updated_at', 'DESC')
			->setFirstResult(($page - 1) * $perPage)
			->setMaxResults($perPage);
		
		return $query->getQuery()->getResult();
	}

	public function getFilteredFandoms($data, $perPage, $page = 1)
	{
		$query = $this->createQueryBuilder('f');
		
		$categoryIdArray = array ();
		$data->getCategories()->first();
		for($i = 0; $i < $data->getCategories()->count(); $i++)
		{
			$categoryIdArray [] = $data->getCategories()
				->current()
				->getId();
			$data->getCategories()->next();
		}
		
		$query->select('f, SIZE(f.chapters) AS chapter_count');
		
		for($i = 0; $i < count($categoryIdArray); $i++)
		{
			$query->orWhere(':c_id' . $i . ' MEMBER OF f.categories')->setParameter(
					':c_id' . $i, $categoryIdArray [$i]);
		}
		
		if ($data->getFandomType())
		{
			$query->andWhere($query->expr()
				->eq('f.fandom_type', ':type'))
				->setParameter(':type', $data->getFandomType());
		}
		if ($data->getTitle())
		{
			$query->andWhere($query->expr()
				->like('f.title', ':title'))
				->setParameter(':title', '%' . $data->getTitle() . '%');
		}
		if ($data->getDescription())
		{
			$query->andWhere($query->expr()
				->like('f.description', ':description'))
				->setParameter(':description', '%' . $data->getDescription() . '%');
		}
		
		$query->orderBy('f.updated_at', 'DESC')
		->setFirstResult(($page - 1) * $perPage)
		->setMaxResults($perPage);
		
		// $query->andWhere(
		// $query->expr()->andX(
		// $query->expr()->eq('f.fandom_type', ':type'),
		// $query->expr()->like('f.title', ':title'),
		// $query->expr()->like('f.description', ':description')));
		// $query->setParameter(':type', $data->getFandomType())
		// ->setParameter(':title', '%'.$data->getTitle().'%')
		// ->setParameter(':description', '%'.$data->getDescription().'%');
		
		return $query->getQuery()->getResult();
	}

	public function findFandoms($perPage, $page = 1)
	{
		$query = $this->createQueryBuilder('f');
		
		$query->select('f, SIZE(f.chapters) AS chapter_count')
			->orderBy('f.updated_at', 'DESC')
			->setFirstResult(($page - 1) * $perPage)
			->setMaxResults($perPage);
		
		return $query->getQuery()->getResult();
	}

	public function findUserFandom($fandomId, $user)
	{
		$query = $this->createQueryBuilder('f');
		
		$query->select('f')
			->where(
				$query->expr()
					->andX($query->expr()
					->eq('f.user', ':user'), $query->expr()
					->eq('f.id', ':id')))
			->setParameter(':user', $user)
			->setParameter(':id', $fandomId);
		
		return $query->getQuery()->getOneOrNullResult();
	}

	public function getTotalFandoms()
	{
		return $this->getEntityManager()
			->createQuery('SELECT COUNT(f.id) FROM FictionFandomBundle:Fandom f')
			->getSingleScalarResult();
	}

	public function getTotalFilteredFandoms($data)
	{
		$query = $this->createQueryBuilder('f');
		$data->getCategories()->first();
		$categoryIdArray = array ();
		for($i = 0; $i < $data->getCategories()->count(); $i++)
		{
			$categoryIdArray [] = $data->getCategories()
				->current()
				->getId();
			$data->getCategories()->next();
		}
		
		$query->select('COUNT(f.id)');
		
		for($i = 0; $i < count($categoryIdArray); $i++)
		{
			$query->orWhere(':c_id' . $i . ' MEMBER OF f.categories')->setParameter(
					':c_id' . $i, $categoryIdArray [$i]);
		}
		
		if ($data->getFandomType())
		{
			$query->andWhere($query->expr()
				->eq('f.fandom_type', ':type'))
				->setParameter(':type', $data->getFandomType());
		}
		if ($data->getTitle())
		{
			$query->andWhere($query->expr()
				->like('f.title', ':title'))
				->setParameter(':title', '%' . $data->getTitle() . '%');
		}
		if ($data->getDescription())
		{
			$query->andWhere($query->expr()
				->like('f.description', ':description'))
				->setParameter(':description', '%' . $data->getDescription() . '%');
		}
		
		return $query->getQuery()->getSingleScalarResult();
	}

	public function getTotalChildFandoms($fandomId)
	{
		$query = $this->createQueryBuilder('f');
		
		$query->select('COUNT(f.id)')
			->leftJoin('f.parents', 'p', 'WHERE', 'p.id = :id')
			->setParameter(':id', $fandomId);
		
		return $query->getQuery()->getSingleScalarResult();
	}
}
