create_story:
  path: /{worldId}/stories/create
  defaults: { _controller: FictionStoryBundle:Story:createStory }
  methods: [GET, POST]
  requirements:
    worldId: \d+
    
edit_story:
  path: /stories/{storyId}/edit
  defaults: { _controller: FictionStoryBundle:Story:editStory }
  methods: [GET, PUT]
  requirements:
    storyId: \d+
    
delete_story:
  path: /stories/{storyId}/delete
  defaults: { _controller: FictionStoryBundle:Story:deleteStory }
  methods: [GET, DELETE]
  requirements:
    storyId: \d+
    
delete_confirm_story:
  path: /stories/{storyId}/delete/confirm
  defaults: { _controller: FictionStoryBundle:Story:deleteConfirmStory }
  methods: [GET, DELETE]
  requirements:
    storyId: \d+
   
create_chapter:
  path: /stories/{storyId}/chapter/create
  defaults: { _controller: FictionStoryBundle:Chapter:createChapter }
  methods: [GET, POST]
  requirements:
    storyId: \d+
    
edit_chapter:
  path: /stories/{storyId}/chapter/{chapterNumber}/edit
  defaults: { _controller: FictionStoryBundle:Chapter:editChapter }
  methods: [GET, PUT]
  requirements:
    storyId: \d+
    chapterNumber: \d+
    
#user_stories:
  #path: /stories
  #defaults: { _controller: FictionStoryBundle:Story:userStories }
  #methods: [GET]
  #requirements: