create_fandom:
  path: /fandoms/create
  defaults: { _controller: FictionFandomBundle:Fandom:createFandom }
  requirements: 
    
edit_fandom:
  path: /fandoms/{fandomId}/edit
  defaults: { _controller: FictionFandomBundle:Fandom:editFandom }
  requirements:
    fandomId: \d+
    
delete_fandom:
  path: /fandoms/{fandomId}/delete
  defaults: { _controller: FictionFandomBundle:Fandom:deleteFandom }
  requirements:
    fandomId: \d+
    
delete_confirm_fandom:
  path: /fandoms/{fandomId}/delete/confirm
  defaults: { _controller: FictionFandomBundle:Fandom:deleteConfirmFandom }
  requirements:
    fandomId: \d+
   
create_chapter:
  path: /fandoms/{fandomId}/chapter/create
  defaults: { _controller: FictionFandomBundle:Chapter:createChapter }
  requirements:
    fandomId: \d+
    
edit_chapter:
  path: /fandoms/{fandomId}/chapter/{chapterNumber}/edit
  defaults: { _controller: FictionFandomBundle:Chapter:editChapter }
  requirements:
    fandomId: \d+
    chapterNumber: \d+
    
user_fandoms:
  path: /fandoms
  defaults: { _controller: FictionFandomBundle:Fandom:userFandoms }
  requirements: